name: Publish image to hub

on:
  push:
    branches: [ automount ]
  pull_request:
    branches: [ automount ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      uses: ilteoood/docker_buildx@master
      with:
        publish: true
        imageName: rinex20/ntripcaster
        platform: linux/amd64,linux/arm64 # 你准备构建的镜像平台
        tag: automount # 默认latest，可以针对平台，修改tag
        dockerUser: ${{ secrets.DOCKER_USERNAME }} # docker hub userid
        dockerPassword: ${{ secrets.DOCKER_PASSWORD }}
